# Basic Config
name: BriceChou
author: BriceChou

url: "https://bricechou.github.io"
baseurl: ""
title: Listen to BriceChou
email: bricechou@gmail.com
description: >
  Sometimes talking, sometimes coding and always gaming.

avatar: https://avatars2.githubusercontent.com/u/8147837?s=460&v=4
copyright: 'Copyright &copy; 2018 BriceChou. All Rights Reserved.'

# Build settings
markdown: kramdown
permalink: pretty
encoding: utf-8

# Footer links
footer-links:
  weibo: bricechou
  email: bricechou@gmail.com
  github: bricechou
  instagram:
  linkedin: 
  stackoverflow: 
  youtube: 
  facebook: 
  twitter: bricechou
  skype: bricechou 

social:
  - title: weibo
    url: https://www.weibo.com/BriceChou
  - title: github
    url: https://www.github.com/BriceChou
