encoding: utf-8

name: BriceChou
url: "https://bricechou.github.io"
title: Listen to BriceChou
description: "Sometimes talking, sometimes coding and always gaming." 
avatar: https://avatars2.githubusercontent.com/u/8147837?s=460&v=4
    
github: bricechou
disqus:

url:
baseurl: ""
google_analytics: 'UA-49627206-1'

footer-links: 
  weibo: bricechou
  email: bricechou@gmail.com
  github: bricechou
  instagram:
  linkedin: 
  stackoverflow: 
  youtube: 
  facebook: 
  twitter: bricechou
  skype: bricechou 

permalink: /:title/

# Jekyll version
version: v1.2.0
