# Basic Config
name: BriceChou
author: BriceChou

url: "https://bricechou.github.io"
baseurl: ""
title: Listen to BriceChou
email: bricechou@gmail.com
description: >
  Sometimes learning, sometimes coding and always gaming.

avatar: https://avatars2.githubusercontent.com/u/8147837?s=460&v=4
copyright: 'Copyright &copy; 2018 BriceChou. All Rights Reserved.'

# Build settings
markdown: kramdown
permalink: pretty
encoding: utf-8

# Footer links
footer-links:
  email: bricechou@gmail.com
  github: bricechou
  skype: bricechou 

social:
  - icon: paper-plane
    title: MailTo
    url: mailto:bricechou@gmail.com
  - icon: github
    title: github
    url: https://www.github.com/BriceChou
