# Basic Config
# name: BriceChou
# author: BriceChou
url: ""
# baseurl: "bricechou.github.io"
title: Listen to BriceChou
email: bricechou@gmail.com
description: >
  No BUG, no code, no one.
avatar: https://avatars2.githubusercontent.com/u/8147837?s=460&v=4
copyright: "Copyright &copy; 2018 - 2020 BriceChou. All Rights Reserved."

# Build settings
markdown: kramdown
permalink: /archivers/:title
encoding: utf-8
paginate: 5
paginate_path: "page:num"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

highlighter: rouge

# Markdown Processing
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Footer links
footer-links:
  email: bricechou@gmail.com
  github: bricechou
  skype: bricechou

social:
  - icon: paper-plane
    title: MailTo
    url: mailto:bricechou@gmail.com
  - icon: github
    title: github
    url: https://www.github.com/BriceChou
